### PR TITLE
XP bar updated

### PR DESCRIPTION
**Pull request by Sonky108**
Updated xp bar, to reflect Dragonflight. No rested xp yet, though.

### CODE REVIEW

**Comment by Sonky108** [comment]
Added rested xp. 
Befor
image

**Comment by Sonky108** [comment]
Added rested xp.

Before pull request:
image

After pull request:
image

**Comment by Karl-HeinzSchneider** [comment]
Looks nice!
The same thing i wrote in the other PR #10 applies.

The bar texture is way better, and it looks like retail, but i like the bigger bar better, so i might adjust the height later. The XP and rep bar are one of the first bigger things i wrote, but i'm not really happy with them; they are overdue for a rewrite, and i'm also planing to add few new features to them.

You could rewrite the XP bar update for the new system if you have the time/want to do it, or i would start a rewite in like a week; let me know what you think!

**Comment by Sonky108** [comment]
Adjusted to new version. Yea, I also think that the bar is a little bit to small, but I've tried to use available textures 1:1 and in retail it's not longer than action bar. Here are example of retail and classic with that PR

Classic:
WoWScrnShot_041723_231432

Retail:
WoWScrnShot_041723_231426

**Comment by Sonky108** [comment]
Sure, I can rewrite the XP bar to the new system, but I'm not sure what does it mean :P you mean as a separate module? Or adding some customization options?

**Comment by Karl-HeinzSchneider** [comment]
I merged it, but will start working on a bigger rework of the XP/Reputation bar.

**Pull request merged**
