### PR TITLE
Enables zooming minimap using mouse wheel

### PR DESCRIPTION
**Pull request by Sonky108**
I've never done anything in lua, so feel free to discard the pull request. As title says, the change allows user to zoom minimap using mouse wheel

### CODE REVIEW

**Comment by Sonky108** [comment]
Also I'm working on showing resources on bars if you are interested :) 

image

**Comment by Karl-HeinzSchneider** [comment]
Thanks for the contribution! I fixed the code, and its nearly identical to the original blizzard code.
Will ship it with the new update this weekend.

**Comment by Karl-HeinzSchneider** [comment]
> Also I'm working on showing resources on bars if you are interested :)
> 
> image

The numerical display? You can enable that under Interface Options > Display > Status Text,  but the anchors are not aligned right now to the new layout (i use default without any text).

**Comment by Sonky108** [comment]
Oh, somehow I missed that option, haha. Anyway, that was good learning experience. Thanks!

**Pull request merged**
