### PR TITLE
Feature/bags expand

### PR DESCRIPTION
**Pull request by Sonky108**
Adds arrow next to the main bag to show/hide rest of the bags

bags

### CODE REVIEW

**Comment by Karl-HeinzSchneider** [comment]
Hey,
looks nice!
I would merge it, but i made a **major** refactor in the last two days, tl:dr: using Ace3 with modules.
The code is nearly identical, i copied most of it over (with minor cleanup, removed old comments etc), and integrated it into the Ace3 module system. It was the first time using Ace3, so it's still a work in progress. 

The goal was better customization, so i merged a few of my old modules into less, bigger modules; e.g. Micromenu.lua is now in Modules/Actionbar.lua . Merging your PR into this would be a bit of a nightmare (the files you worked in are gone etc), so i would close this after i push the refactor to the main branch. You could rewrite and make an new PR, should be no problem with a few infos:

I guess you haven't used Ace3 either (you said this was your first LUA experience), so some of it might be a bit confusing, but after a few days it makes sense. I implemented the default profile and interface options system, which looks a bit like magic, but you could start like this:

_Modules/Actionbar.lua_ `line 10: defaults` holds default settings for that module, so you can add a variable with 
`local defaults  = { 
... ,
 bagsExpanded= true,
}`

and call your `Module.BagBarExpandToggled(bagsExpanded)` (add the `Module.`) under  `line 147: function Module:ApplySettings()`, e.g. `Module.BagBarExpandToggled(db.bagsExpanded)`
This function gets called everytime some config value is updated/loaded.

`function CreateBagExpandButton()` should be created as  `function Module.CreateBagExpandButton()` and called under `Line 1417: function Module.Wrath()`  (code is only duplicated under Module.Era() if Era needs something different, so not in this instance), which gets called in `line 134: function Module:OnEnable()`.

The `OnClick()` needs to update the variable, so i think the best way would be to just call `setOption({'bagsExpanded'}, not Module.db.profile.bagsExpanded)`. I would combine `BagBarExpandToggled` and `UpdateBagBarToggleOrientation`; the listen for `BAG_UPDATE_DELAYED` should be unneeded (which btw gets called a lot, e.g. when you move one item in your inventory)

This should get you going!
Let me know if you need anything.

PS: I could have integrated the feature in less time than typing this comment took, but i didn't want to remove your contribution from the code history!

**Comment by Sonky108** [comment]
The problem is that if don't wait for BAG_UPDATE_DELAYED on the start when bags were hidden it looks like this: 
image
and I'm not sure what shows keyring

**Comment by Sonky108** [comment]
Adjusted to new version. It looks quite powerful!

**Comment by Karl-HeinzSchneider** [comment]
> The problem is that if don't wait for BAG_UPDATE_DELAYED on the start when bags were hidden it looks like this: image and I'm not sure what shows keyring

Ah ok, but it might be something with the load order.
Will review later!

Btw, are you using VS Code? I'm using [this plugin](https://marketplace.visualstudio.com/items?itemName=autsing.lua-format-extension) to auto format .lua on save, so the style will be consistent, so e.g. your line 1379 or 1405-1407 might get a formatting commit soon^^
[This](https://marketplace.visualstudio.com/items?itemName=Septh.wow-bundle) is also nice.

**Comment by Karl-HeinzSchneider** [comment]
I guess `frame:UnregisterEvent('BAG_UPDATE_DELAYED')` after first setup would be the easiest solution; seems to work.

**Pull request merged**
